---
title: "recalculate distance and elevation"
output: html_notebook
---

Prep workspace and load data
```{r}
rm(list = ls()); gc()
require(raster)
require(ggplot2) # load packages
require(rnaturalearth)
require(rnaturalearthdata)
require(viridis)
require(sf)
require(rgdal)

# for mountain mass and water mass cirles
lonlat2UTM = function(lonlat) {
  utm = (floor((lonlat[1] + 180) / 6) %% 60) + 1
  if(lonlat[2] > 0) {
    utm + 32600
  } else{
    utm + 32700
  }
}

#main dataframe
load("/Users/boterolab1/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Analyze_Processed_Cluster_Outputs/dataforpca.Rdata")
mydata <- mydata_e

# pam data
load("/Users/boterolab1/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/PREP/PAM/Data/cbPAM.rdata")
load("/Users/boterolab1/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/PREP/PAM/Data/LonLat_BirdPAM_raster.rdata")
crs(LonLat_BirdPAM_raster)

# elevation data
load("/Users/boterolab1/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/PREP/Topo/Data/Elev_raster.rdata")
crs(Elev_raster)

# world coastline for maps
world <- ne_coastline(scale = "medium", returnclass = "sf")

# global mountains for mountain mass
mtns <- readOGR(dsn="~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Other_Input_Data/GMBA", layer="GMBA Mountain Inventory_v1.2-World", verbose = FALSE)
mtns <- st_as_sf(mtns)
wtr <- read_sf("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Other_Input_Data/ne_50m_ocean/ne_50m_ocean.shp")

buffer_ranges<-c(seq(from = 0, to = 200, by  = 50)[-1], seq(from=0, to = 3000, by = 250)[-1]) * 1000
bufferdata_sp1_mtn <- matrix(nrow = nrow(mydata), ncol = length(buffer_ranges))
bufferdata_sp1_wtr <- matrix(nrow = nrow(mydata), ncol = length(buffer_ranges))
bufferdata_sp2_mtn <- bufferdata_sp1_mtn
bufferdata_sp2_wtr <- bufferdata_sp1_wtr
```

# calculate pairdistance minimum and pairdistance btm 25%
```{r, message=F, warning=F}
mydata$pd0 <- NA
mydata$pd25 <- NA
mydata$meanEle <- NA
for (i in 1:nrow(mydata)){
  # species 1 ----
  sp1 <- cbPAM[,c("Longitude(x)","Latitude(y)",mydata$Species.1bl[i])]
  sp1 <- as.data.frame(sp1[sp1[,3] == 1,]); colnames(sp1) <- c("lon", "lat", "pres")
  sp1 <- data.frame(cbind(lon=sp1$lon, lat = sp1$lat)); sp1 <- sp1[complete.cases(sp1),]
  coordinates(sp1) <- c("lon","lat"); crs(sp1)<-crs(LonLat_BirdPAM_raster)
  sp1mean <- rgeos::gCentroid(sp1) # mean of projected coordinates, see: https://stackoverflow.com/questions/35720614/gcentroid-rgeos-r-vs-actual-centroid-in-python)
  sp1EPSG_2_UTM <- as.numeric(lonlat2UTM(sp1mean@coords)) # To see the UTM #st_crs(EPSG_2_UTM)$proj4string
  sp1mean_proj <- st_transform(st_as_sf(sp1mean), sp1EPSG_2_UTM)
  
  # species 2 ----
  sp2 <- cbPAM[,c("Longitude(x)","Latitude(y)",mydata$Species.2bl[i])]
  sp2 <- as.data.frame(sp2[sp2[,3] == 1,]); colnames(sp2) <- c("lon", "lat", "pres")
  sp2 <- data.frame(cbind(lon=sp2$lon, lat = sp2$lat)); sp2 <- sp2[complete.cases(sp2),]
  coordinates(sp2) <- c("lon","lat"); crs(sp2)<-crs(LonLat_BirdPAM_raster)
  sp2mean <- rgeos::gCentroid(sp2) # mean of projected coordinates
  sp2EPSG_2_UTM <- as.numeric(lonlat2UTM(sp2mean@coords))
  sp2mean_proj <- st_transform(st_as_sf(sp2mean), sp2EPSG_2_UTM)
  
  # calculate wtr mass and mtn mass matrices.
  for(j in 1:length(buffer_ranges)){
    # species 1 ----------------------------------------------------------------
    sp1mean_proj_with_b_km_buffer <- st_buffer(sp1mean_proj,dist=buffer_ranges[j])
    # mtns ---
    mtns_in_buffer_b_km <- st_intersection(st_make_valid(sf::st_transform(sp1mean_proj_with_b_km_buffer, crs=st_crs(mtns))), st_make_valid(mtns))
    area_in_buffer_b_km <- sum(as.numeric(st_area(mtns_in_buffer_b_km)))
    bufferdata_sp1_mtn[i, j] <- area_in_buffer_b_km
    # water ----
    wtr_in_buffer_b_km <- st_intersection(st_make_valid(sf::st_transform(sp1mean_proj_with_b_km_buffer, crs=st_crs(wtr))), st_make_valid(wtr))
    area_in_buffer_b_km <- sum(as.numeric(st_area(wtr_in_buffer_b_km)))
    bufferdata_sp1_wtr[i, j] <- area_in_buffer_b_km
    
    # species 2 ----------------------------------------------------------------
    sp2mean_proj_with_b_km_buffer <- st_buffer(sp2mean_proj,dist=buffer_ranges[j])
    # mtns ---
    mtns_in_buffer_b_km <- st_intersection(st_make_valid(sf::st_transform(sp2mean_proj_with_b_km_buffer, crs=st_crs(mtns))), st_make_valid(mtns))
    area_in_buffer_b_km <- sum(as.numeric(st_area(mtns_in_buffer_b_km)))
    bufferdata_sp2_mtn[i, j] <- area_in_buffer_b_km
    # water ----
    wtr_in_buffer_b_km <- st_intersection(st_make_valid(sf::st_transform(sp2mean_proj_with_b_km_buffer, crs=st_crs(wtr))), st_make_valid(wtr))
    area_in_buffer_b_km <- sum(as.numeric(st_area(wtr_in_buffer_b_km)))
    bufferdata_sp2_wtr[i, j] <- area_in_buffer_b_km
  }

  # pair distance --------------------------------------------------------------
  pd <- raster::pointDistance(sp1@coords, sp2@coords, lonlat = T, allpairs = T)
  mydata$pd0[i] <- min(pd)
  mydata$pd25[i] <- quantile(pd, 0.25)
  
  # pair elevation -------------------------------------------------------------
  mydata$meanEle[i] <- mean(c(mean(extract(Elev_raster, sp1), na.rm=T), mean(extract(Elev_raster, sp2), na.rm=T)), na.rm = T)
  # if(i %% 10 == 0){print(i)}
  print(i)
}

for(i in 1:nrow(bufferdata_sp1_mtn)) {
  bufferdata_sp1_mtn[i,] <- bufferdata_sp1_mtn[i,] / buffer_ranges
  bufferdata_sp2_mtn[i,] <- bufferdata_sp2_mtn[i,] / buffer_ranges
  bufferdata_sp1_wtr[i,] <- bufferdata_sp1_wtr[i,] / buffer_ranges
  bufferdata_sp2_wtr[i,] <- bufferdata_sp2_wtr[i,] / buffer_ranges
}
mydata$mtn_mass2 <- rowMeans(cbind(rowSums(bufferdata_sp1_mtn), rowSums(bufferdata_sp2_mtn)))
mydata$wtr_mass2 <- rowMeans(cbind(rowSums(bufferdata_sp1_wtr), rowSums(bufferdata_sp2_wtr)))
getwd()
save(mydata, file = "newdataforpca.Rdata")
```

check diagnostic plots
```{r}
plot(mydata$pd0 ~ mydata$distance)
plot(mydata$pd25 ~ mydata$distance)
plot(mydata$pd0 ~ mydata$pd25)

plot(wtr_mass ~ wtr_mass2, data = mydata[mydata$wtr_mass2 < 2e8,])
plot(mtn_mass ~ mtn_mass2, data = mydata)

size = 2
alpha = 0.7
x1 <- ggplot(world)+ geom_sf() + geom_point(data = mydata[order(mydata$pd0, decreasing = F),], aes(y=lat, x=lon, color = pd0), alpha = alpha, size = size)+ 
  ggtitle("pd0")+scale_color_viridis()
print(x1)

x1 <- ggplot(world)+ geom_sf() + geom_point(data = mydata[order(mydata$pd25, decreasing = F),], aes(y=lat, x=lon, color = pd25), alpha = alpha, size = size)+ 
  ggtitle("pd25")+scale_color_viridis()
print(x1)

x1 <- ggplot(world)+ geom_sf() + geom_point(data = mydata[order(mydata$meanEle, decreasing = F),], aes(y=lat, x=lon, color = meanEle), alpha = alpha, size = size)+ 
  ggtitle("meanEle")+scale_color_viridis()
print(x1)

x1 <- ggplot(world)+ geom_sf() + geom_point(data = mydata[order(mydata$mtn_mass2, decreasing = F),], aes(y=lat, x=lon, color = mtn_mass2), alpha = alpha, size = size)+ 
  ggtitle("mtn_mass2")+scale_color_viridis()
print(x1)

x1 <- ggplot(world)+ geom_sf() + geom_point(data = mydata[mydata$wtr_mass2 < 2e8,], aes(y=lat, x=lon, color = wtr_mass2), alpha = alpha, size = size)+ 
  ggtitle("wtr_mass2")+scale_color_viridis()
print(x1)
```

