---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r, include=F}
# top matter

rm(list = ls()); gc()
require(ggplot2) # load packages
require(EnvStats)
require(psych)
require(geiger)
require(phylolm)
require(sensiPhy)
require(rnaturalearth)
require(rnaturalearthdata)
require(viridis)
require(tidyr)
require(raster)

vlog <- function(x){
  log( x + abs(min( x , na.rm = T)) + 1)
}

myBCtransform <- function(myvector) {
  # shift scale to positive numbers and identify optimal lambda for box-cox transformation
  mylambda <- boxcox(as.numeric(myvector)-min(as.numeric(myvector))+1, optimize = T)$lambda
  
  # transform
  myvector <- scale(boxcoxTransform(as.numeric(myvector)-min(as.numeric(myvector))+1, mylambda))
  return (scale(myvector))
}

load("/Users/boterolab1/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Analyze_Processed_Cluster_Outputs/newdataforpca.Rdata")
```

```{r, include=F}
# add another metric for range size (use only this or boundary length OR neither. NOT BOTH).

load("/Users/boterolab1/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/PREP/PAM/Data/cbPAM.rdata")
load("/Users/boterolab1/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/PREP/PAM/Data/LonLat_BirdPAM_raster.rdata")
mydata$npamcells <- NA
for(i in 1:nrow(mydata)){
  sp1 <- cbPAM[,c("Longitude(x)","Latitude(y)",mydata$Species.1bl[i])]
sp1 <- as.data.frame(sp1[sp1[,3] == 1,]); colnames(sp1) <- c("lon", "lat", "pres")
sp1 <- data.frame(cbind(lon=sp1$lon, lat = sp1$lat)); sp1 <- sp1[complete.cases(sp1),]
temp1 <- nrow(sp1)

sp2 <- cbPAM[,c("Longitude(x)","Latitude(y)",mydata$Species.1bl[i])]
sp2 <- as.data.frame(sp2[sp2[,3] == 1,]); colnames(sp2) <- c("lon", "lat", "pres")
sp2 <- data.frame(cbind(lon=sp2$lon, lat = sp2$lat)); sp2 <- sp2[complete.cases(sp2),]
temp2 <- nrow(sp2)
mydata$npamcells[i] <- mean(c(temp1, temp2), na.rm = T)
}

# hist(mydata$npamcells)
mydata$npamcells <- scale(myBCtransform(mydata$npamcells))
# hist(mydata$npamcells)
```

```{r, include=F}
# PCA predictor Prep

# hist(mydata$tas_breadth)
mydata$tas_breadth <- scale(myBCtransform(mydata$tas_breadth))
# hist(mydata$tas_breadth)

# hist(mydata$tas_position)
mydata$tas_position <- scale(myBCtransform(mydata$tas_position))
# hist(mydata$tas_position)

# hist(mydata$pcp_breadth)
mydata$pcp_breadth <- scale(mydata$pcp_breadth)
# hist(mydata$pcp_breadth)

# hist(mydata$pcp_position)
mydata$pcp_position <- scale(mydata$pcp_position)
# hist(mydata$pcp_position)

# hist(mydata$mtn_mass2)
mydata$mtn_mass2 <- scale(myBCtransform(mydata$mtn_mass2))
# hist(mydata$mtn_mass2)

# hist(mydata$wtr_mass2)
mydata$wtr_mass2 <- scale(myBCtransform(mydata$wtr_mass2))
# hist(mydata$wtr_mass2)

# hist(mydata$dispersal_ability)
mydata$dispersal_ability <- scale(myBCtransform(mydata$dispersal_ability))
# hist(mydata$dispersal_ability)

# hist(mydata$pair_age)
mydata$pair_age <- scale(myBCtransform(mydata$pair_age))
# hist(mydata$pair_age)

# hist(mydata$pd0)
mydata$pd0 <- scale(myBCtransform(mydata$pd0))
# hist(mydata$pd0)

# hist(mydata$pd25)
mydata$pd25 <- scale(myBCtransform(mydata$pd25))
# hist(mydata$pd25)

# hist(mydata$boundary_length)
mydata$boundary_length <- scale(myBCtransform(mydata$boundary_length))
# hist(mydata$boundary_length)

# hist(mydata$meanEle)
mydata$meanEle <- scale(myBCtransform(mydata$meanEle))
# hist(mydata$meanEle)
```

```{r, include=F}
load("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Other_Input_Data/BirdTrees/BirdTrees.Rdata")
# first we deal with phylogenetic non-independence by using the tip of one of the
# species in each pair as the placement of the pair in the tree
CHK <- geiger::name.check(trees[[1]], mydata, data.names = mydata$Species.1)

world <- ne_coastline(scale = "medium", returnclass = "sf")
size = 0.9
alpha = 0.66
```

# PCA 1
```{r, message=F, warning=F}
myPCA <- principal(mydata[,c('tas_breadth', 'tas_position', 'pcp_breadth',
                             'pcp_position', 'mtn_mass2', 'wtr_mass2', "npamcells",
                             'dispersal_ability', 'pair_age', "pd0","pd25", 'meanEle')], nfactors = 11, rotate = "none")
myPCA$loadings
mydata$PC1 <- myPCA$scores[,'PC1']
mydata$PC2 <- myPCA$scores[,'PC2']
mydata$PC3 <- myPCA$scores[,'PC3']
mydata$PC4 <- myPCA$scores[,'PC4']
mytree <- drop.tip(trees[[i]], CHK$tree_not_data)
mymod <- phylolm(I(log(cost)) ~ PC1 + PC2 + PC3 + PC4,
                 phy = mytree, model = 'lambda', data = mydata)
summary(mymod)
```
<br><br><br><br><br>

# PCA 2
```{r, message=F, warning=F}
myPCA <- principal(mydata[,c('tas_breadth', 'tas_position', 'pcp_breadth',
                             'pcp_position', 'mtn_mass2', 'wtr_mass2', "npamcells",
                             'dispersal_ability', 'pair_age', "pd25", 'meanEle')], nfactors = 10, rotate = "none")
myPCA$loadings
mydata$PC1 <- -myPCA$scores[,'PC1']
mydata$PC2 <- myPCA$scores[,'PC2']
mydata$PC3 <- myPCA$scores[,'PC3']
mydata$PC4 <- myPCA$scores[,'PC4']
mytree <- drop.tip(trees[[i]], CHK$tree_not_data)
mymod <- phylolm(I(log(cost)) ~ PC1 + PC2 + PC3 + PC4,
                 phy = mytree, model = 'lambda', data = mydata)
summary(mymod)
```
<br><br><br><br><br>

# PCA 4
```{r, message=F, warning=F}
myPCA <- principal(mydata[,c('tas_breadth', 'tas_position', 'pcp_breadth',
                             'pcp_position', 'mtn_mass2', 'wtr_mass2', "boundary_length",
                             'dispersal_ability', 'pair_age', "pd25", 'meanEle')], nfactors = 10, rotate = "none")
myPCA$loadings
mydata$PC1 <- myPCA$scores[,'PC1']
mydata$PC2 <- myPCA$scores[,'PC2']
mydata$PC3 <- myPCA$scores[,'PC3']
mydata$PC4 <- myPCA$scores[,'PC4']
mytree <- drop.tip(trees[[i]], CHK$tree_not_data)
mymod <- phylolm(I(log(cost)) ~ PC1 + PC2 + PC3 + PC4,
                 phy = mytree, model = 'lambda', data = mydata)
summary(mymod)
```
<br><br><br><br><br>

# PCA 5
```{r, message=F, warning=F}
myPCA <- principal(mydata[,c('tas_breadth', 'tas_position', 'pcp_breadth',
                             'pcp_position', 'mtn_mass2', 'wtr_mass2', "boundary_length",
                             'dispersal_ability', 'pair_age', "pd0", 'meanEle')], nfactors = 10, rotate = "none")
myPCA$loadings
mydata$PC1 <- -myPCA$scores[,'PC1']
mydata$PC2 <- myPCA$scores[,'PC2']
mydata$PC3 <- myPCA$scores[,'PC3']
mydata$PC4 <- myPCA$scores[,'PC4']
mytree <- drop.tip(trees[[i]], CHK$tree_not_data)
mymod <- phylolm(I(log(cost)) ~ PC1 + PC2 + PC3 + PC4,
                 phy = mytree, model = 'lambda', data = mydata)
summary(mymod)
```
<br><br><br><br><br>

# PCA 7
```{r, message=F, warning=F}
myPCA <- principal(mydata[,c('tas_breadth', 'tas_position', 'pcp_breadth',
                             'pcp_position', 'mtn_mass2', 'wtr_mass2',
                             'dispersal_ability', 'pair_age', "pd0", "pd25")], nfactors = 9, rotate = "none")
myPCA$loadings
mydata$PC1 <- -myPCA$scores[,'PC1']
mydata$PC2 <- -myPCA$scores[,'PC2']
mydata$PC3 <- myPCA$scores[,'PC3']
mydata$PC4 <- myPCA$scores[,'PC4']
mytree <- drop.tip(trees[[i]], CHK$tree_not_data)
mymod <- phylolm(I(log(cost)) ~ PC1 + PC2 + PC3 + PC4,
                 phy = mytree, model = 'lambda', data = mydata)
summary(mymod)
```
<br><br><br><br><br>

# PCA 8
```{r, message=F, warning=F}
myPCA <- principal(mydata[,c('tas_breadth', 'tas_position', 'pcp_breadth',
                             'pcp_position', 'mtn_mass2', 'wtr_mass2',
                             'dispersal_ability', 'pair_age', "pd25")], nfactors = 8, rotate = "none")
myPCA$loadings
mydata$PC1 <- -myPCA$scores[,'PC1']
mydata$PC2 <- myPCA$scores[,'PC2']
mydata$PC3 <- myPCA$scores[,'PC3']
mydata$PC4 <- myPCA$scores[,'PC4']
mytree <- drop.tip(trees[[i]], CHK$tree_not_data)
mymod <- phylolm(I(log(cost)) ~ PC1 + PC2 + PC3 + PC4,
                 phy = mytree, model = 'lambda', data = mydata)
summary(mymod)
```
<br><br><br><br><br>

# PCA 9
```{r, message=F, warning=F}
myPCA <- principal(mydata[,c('tas_breadth', 'tas_position', 'pcp_breadth',
                             'pcp_position', 'mtn_mass2', 'wtr_mass2',
                             'dispersal_ability', 'pair_age', "pd0")], nfactors = 8, rotate = "none")
myPCA$loadings
mydata$PC1 <- -myPCA$scores[,'PC1']
mydata$PC2 <- myPCA$scores[,'PC2']
mydata$PC3 <- myPCA$scores[,'PC3']
mydata$PC4 <- myPCA$scores[,'PC4']
mytree <- drop.tip(trees[[i]], CHK$tree_not_data)
mymod <- phylolm(I(log(cost)) ~ PC1 + PC2 + PC3 + PC4,
                 phy = mytree, model = 'lambda', data = mydata)
summary(mymod)
```
<br><br><br><br><br>



```{r, include=F}
# Visualize

# ggplot(world)+ geom_sf() + geom_point(data = mydata[order(mydata$PC1, decreasing = F),], aes(y=lat, x=lon, color = PC1), alpha = alpha, size = size)+ 
#   ggtitle("PC1")+scale_color_viridis()
# ggplot(world)+ geom_sf() + geom_point(data = mydata[order(mydata$PC2, decreasing = F),], aes(y=lat, x=lon, color = PC2), alpha = alpha, size = size)+
#   ggtitle("PC2")+scale_color_viridis()
# ggplot(world)+ geom_sf() + geom_point(data = mydata[order(mydata$PC3, decreasing = F),], aes(y=lat, x=lon, color = PC3), alpha = alpha, size = size)+
#   ggtitle("PC3")+scale_color_viridis()
# ggplot(world)+ geom_sf() + geom_point(data = mydata[order(mydata$PC3, decreasing = F),], aes(y=lat, x=lon, color = PC3), alpha = alpha, size = size)+
#   ggtitle("PC4")+scale_color_viridis()
```
 <br><br><br><br><br>

 
 

```{r, include=F}
#for running across many trees. not finished. 

# sensimod <- my_tree_phylm(formula = I(log(cost)) ~ PC1 + PC2 + PC3 + PC4,
#               data = mydata,
#               phy = trees,
#               n.tree = 2, 
#               model = "lambda",
#               track = TRUE,
#               add_median_residuals = TRUE)
# summary(sensimod)
# my_sensimod(sensimod)
```
<br><br><br><br><br>

