---
title: "R Notebook"
output: html_notebook
---

```{r, include=F}
# top matter

rm(list = ls()); gc()
require(ggplot2) # load packages
require(EnvStats)
require(psych)
require(geiger)
require(phylolm)
require(sensiPhy)
require(rnaturalearth)
require(rnaturalearthdata)
require(viridis)
require(tidyr)
require(raster)
require(dplyr)
require(spdep)
require(spatialreg)
require(lasso2)
source("/Users/boterolab1/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Analyze_Processed_Cluster_Outputs/sensiphy_SOURCE.R")
vlog <- function(x){
  log( x + abs(min( x , na.rm = T)) + 1)
}
'%notin%' <- Negate('%in%')

myBCtransform <- function(myvector) {
  # shift scale to positive numbers and identify optimal lambda for box-cox transformation
  mylambda <- boxcox(as.numeric(myvector)-min(as.numeric(myvector))+1, optimize = T)$lambda
  
  # transform
  myvector <- scale(boxcoxTransform(as.numeric(myvector)-min(as.numeric(myvector))+1, mylambda))
  return (scale(myvector))
}

load("/Users/boterolab1/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Analyze_Processed_Cluster_Outputs/newdataforpca.Rdata")
```

Sensitivity Analyses
```{r}
# 1 Pair age (all v. < 8mya (end of uplift of Andes))
# 2 Distance (all v. < 1500*1000) (1500 / 110 = ~ 22 degrees)
# 3 MAT_overlap (> 0% v. > 75% (more restrictive == more conservative for this measure.))
# 4 landgap (all v. nogap) *ALL GAPS ARE < 110km (two water grid cells marked as land for having >50% land @ 0.5 degree resolution.)
```

```{r, include=F}
# add another metric for range size (use only this or boundary length OR neither. NOT BOTH).

load("/Users/boterolab1/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/PREP/PAM/Data/cbPAM.rdata")
load("/Users/boterolab1/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/PREP/PAM/Data/LonLat_BirdPAM_raster.rdata")
mydata$npamcells <- NA
for(i in 1:nrow(mydata)){
  sp1 <- cbPAM[,c("Longitude(x)","Latitude(y)",mydata$Species.1bl[i])]
sp1 <- as.data.frame(sp1[sp1[,3] == 1,]); colnames(sp1) <- c("lon", "lat", "pres")
sp1 <- data.frame(cbind(lon=sp1$lon, lat = sp1$lat)); sp1 <- sp1[complete.cases(sp1),]
temp1 <- nrow(sp1)

sp2 <- cbPAM[,c("Longitude(x)","Latitude(y)",mydata$Species.1bl[i])]
sp2 <- as.data.frame(sp2[sp2[,3] == 1,]); colnames(sp2) <- c("lon", "lat", "pres")
sp2 <- data.frame(cbind(lon=sp2$lon, lat = sp2$lat)); sp2 <- sp2[complete.cases(sp2),]
temp2 <- nrow(sp2)
mydata$npamcells[i] <- mean(c(temp1, temp2), na.rm = T)
}

# hist(mydata$npamcells)
mydata$npamcells <- scale(myBCtransform(mydata$npamcells))
# hist(mydata$npamcells)
```

```{r, include=F}
# PCA predictor Prep

# hist(mydata$tas_breadth)
mydata$tas_breadth <- scale(myBCtransform(mydata$tas_breadth))
# hist(mydata$tas_breadth)

# hist(mydata$tas_position)
mydata$tas_position <- scale(myBCtransform(mydata$tas_position))
# hist(mydata$tas_position)

# hist(mydata$pcp_breadth)
mydata$pcp_breadth <- scale(mydata$pcp_breadth)
# hist(mydata$pcp_breadth)

# hist(mydata$pcp_position)
mydata$pcp_position <- scale(mydata$pcp_position)
# hist(mydata$pcp_position)

# hist(mydata$mtn_mass2)
mydata$mtn_mass2 <- scale(myBCtransform(mydata$mtn_mass2))
# hist(mydata$mtn_mass2)

# hist(mydata$wtr_mass2)
mydata$wtr_mass2 <- scale(myBCtransform(mydata$wtr_mass2))
# hist(mydata$wtr_mass2)

# hist(mydata$dispersal_ability)
mydata$dispersal_ability <- scale(myBCtransform(mydata$dispersal_ability))
# hist(mydata$dispersal_ability)

# hist(mydata$pair_age)
mydata$pair_age <- scale(myBCtransform(mydata$pair_age))
# hist(mydata$pair_age)

# hist(mydata$pd0)
mydata$pd0 <- scale(myBCtransform(mydata$pd0))
# hist(mydata$pd0)

# hist(mydata$pd25)
mydata$pd25 <- scale(myBCtransform(mydata$pd25))
# hist(mydata$pd25)

# hist(mydata$boundary_length)
mydata$boundary_length <- scale(myBCtransform(mydata$boundary_length))
# hist(mydata$boundary_length)

# hist(mydata$meanEle)
mydata$meanEle <- scale(myBCtransform(mydata$meanEle))
# hist(mydata$meanEle)
```