

```{r Top Matter}
rm(list = ls()); invisible(gc())
require(rgdal)
require(sp)
require(raster)
require(reshape2)
require(abind)
mypath <- "~/Box Sync/JMPH/"
```

```{r Load CLUSTER OUTPUTS & Concatonate}
load(paste0(mypath, "ClusterFiles_E/outputs_e/1_Main_Batch_Results_origin_1_to_5000_E.rdata")) # elev outputs base
m_a_bblats_ele <- m_a_bblats_ele_block; rm(m_a_bblats_ele_block)
m_a_bblons_ele <- m_a_bblons_ele_block; rm(m_a_bblons_ele_block)
m_aB_ele_mcosts <- m_aB_ele_mcosts_block; rm(m_aB_ele_mcosts_block)
m_aB_ele_plengths <- m_aB_ele_plengths_block; rm(m_aB_ele_plengths_block)

load(paste0(mypath, "ClusterFiles_T/outputs_t/1_Main_Batch_Results_origin_1_to_5000_T.rdata")) # temp 
m_a_bblats_tmp <- m_a_bblats_tmp_block; rm(m_a_bblats_tmp_block)
m_a_bblons_tmp <- m_a_bblons_tmp_block; rm(m_a_bblons_tmp_block)
m_aB_tmp_mcosts <- m_aB_tmp_mcosts_block; rm(m_aB_tmp_mcosts_block)
m_aB_tmp_plengths <- m_aB_tmp_plengths_block; rm(m_aB_tmp_plengths_block)

load(paste0(mypath, "ClusterFiles_P/outputs_p/1_Main_Batch_Results_origin_1_to_5000_P.rdata")) # precip 
m_a_bblats_pcp <- m_a_bblats_pcp_block; rm(m_a_bblats_pcp_block)
m_a_bblons_pcp <- m_a_bblons_pcp_block; rm(m_a_bblons_pcp_block)
m_aB_pcp_mcosts <- m_aB_pcp_mcosts_block; rm(m_aB_pcp_mcosts_block)
m_aB_pcp_plengths <- m_aB_pcp_plengths_block; rm(m_aB_pcp_plengths_block)

for(i in 2:200){
  load(paste0(mypath, "ClusterFiles_E/outputs_e/", i, "_Main_Batch_Results_origin_1_to_5000_E.rdata")) # elev concat
  m_a_bblats_ele <- rbind(m_a_bblats_ele, m_a_bblats_ele_block); rm(m_a_bblats_ele_block)
  m_a_bblons_ele <- rbind(m_a_bblons_ele, m_a_bblons_ele_block); rm(m_a_bblons_ele_block)
  m_aB_ele_mcosts <- rbind(m_aB_ele_mcosts, m_aB_ele_mcosts_block); rm(m_aB_ele_mcosts_block)
  m_aB_ele_plengths <- rbind(m_aB_ele_plengths, m_aB_ele_plengths_block); rm(m_aB_ele_plengths_block)
  
  load(paste0(mypath, "ClusterFiles_T/outputs_t/", i, "_Main_Batch_Results_origin_1_to_5000_T.rdata")) # temp
  m_a_bblats_tmp <- rbind(m_a_bblats_tmp, m_a_bblats_tmp_block); rm(m_a_bblats_tmp_block)
  m_a_bblons_tmp <- rbind(m_a_bblons_tmp, m_a_bblons_tmp_block); rm(m_a_bblons_tmp_block)
  m_aB_tmp_mcosts <- rbind(m_aB_tmp_mcosts, m_aB_tmp_mcosts_block); rm(m_aB_tmp_mcosts_block)
  m_aB_tmp_plengths <- rbind(m_aB_tmp_plengths, m_aB_tmp_plengths_block); rm(m_aB_tmp_plengths_block)
    
  load(paste0(mypath, "ClusterFiles_P/outputs_p/", i, "_Main_Batch_Results_origin_1_to_5000_P.rdata")) # precip
  m_a_bblats_pcp <- rbind(m_a_bblats_pcp, m_a_bblats_pcp_block); rm(m_a_bblats_pcp_block)
  m_a_bblons_pcp <- rbind(m_a_bblons_pcp, m_a_bblons_pcp_block); rm(m_a_bblons_pcp_block)
  m_aB_pcp_mcosts <- rbind(m_aB_pcp_mcosts, m_aB_pcp_mcosts_block); rm(m_aB_pcp_mcosts_block)
  m_aB_pcp_plengths <- rbind(m_aB_pcp_plengths, m_aB_pcp_plengths_block); rm(m_aB_pcp_plengths_block)
  print(paste0("done ", i))
}
```

```{r Fix SPATH_EXTENTPOINT values and convert to numeric}
m_aB_ele_mcosts[m_aB_ele_mcosts == "sPath_extentpoint"] <- "0.0" # elev fix vals & type
m_aB_ele_mcosts <- type.convert(m_aB_ele_mcosts)
m_aB_ele_plengths[m_aB_ele_plengths == "sPath_extentpoint"] <- "0.0"
m_aB_ele_plengths <- type.convert(m_aB_ele_plengths)
m_aB_ele_gradients <- m_aB_ele_mcosts/m_aB_ele_plengths
m_aB_ele_gradients[is.nan(m_aB_ele_gradients)] <- 0 

m_aB_tmp_mcosts[m_aB_tmp_mcosts == "sPath_extentpoint"] <- "0.0" # temp
m_aB_tmp_mcosts <- type.convert(m_aB_tmp_mcosts)
m_aB_tmp_plengths[m_aB_tmp_plengths == "sPath_extentpoint"] <- "0.0"
m_aB_tmp_plengths <- type.convert(m_aB_tmp_plengths)
m_aB_tmp_gradients <- m_aB_tmp_mcosts/m_aB_tmp_plengths
m_aB_tmp_gradients[is.nan(m_aB_tmp_gradients)] <- 0 

m_aB_pcp_mcosts[m_aB_pcp_mcosts == "sPath_extentpoint"] <- "0.0" # precip
m_aB_pcp_mcosts <- type.convert(m_aB_pcp_mcosts)
m_aB_pcp_plengths[m_aB_pcp_plengths == "sPath_extentpoint"] <- "0.0"
m_aB_pcp_plengths <- type.convert(m_aB_pcp_plengths)
m_aB_pcp_gradients <- m_aB_pcp_mcosts/m_aB_pcp_plengths
m_aB_pcp_gradients[is.nan(m_aB_pcp_gradients)] <- 0 
```

```{r Save}
setwd("~/Box Sync/JMPH/Process_Cluster_Outputs/Data")
save(m_a_bblats_ele, m_a_bblons_ele, m_aB_ele_mcosts, m_aB_ele_plengths, m_aB_ele_gradients, file = "Elevation_Results_Concat.rdata")
save(m_a_bblats_tmp, m_a_bblons_tmp, m_aB_tmp_mcosts, m_aB_tmp_plengths, m_aB_tmp_gradients, file = "Temperature_Results_Concat.rdata")
save(m_a_bblats_pcp, m_a_bblons_pcp, m_aB_pcp_mcosts, m_aB_pcp_plengths, m_aB_pcp_gradients, file = "Precipitation_Results_Concat.rdata")
```

