

```{r Top Matter}
rm(list = ls()); invisible(gc())

require(rgdal)
require(sp)
require(raster)
require(reshape2)
require(abind)
require(purrr)

setwd("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/PREP/MainDataFrame/Data")
load("a_mats_UNM_basic.rdata"); rm(m_a_eles, m_a_slop, m_a_aspe)
load("cooneyp.rdata")


setwd("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Process_Cluster_Outputs/Data")
load(file = "Elevation_Results_Concat.rdata"); rm(m_a_bblats_ele, m_a_bblons_ele)
load(file = "MAT_Results_Concat.rdata"); rm(m_a_bblats_MAT, m_a_bblons_MAT)

`%!in%` <- compose(`!`, `%in%`)
```




```{r Create a SIMPLE 1 row per species dataset}
sum(cooneyp$Species.1bl != rownames(m_aB_ele_mcosts)) # confirm identical n rows and sort order.

# retain interest columns only.
mydata <- cooneyp[,c("Species.1" , "Species.2", "Species.1bl" , "Species.2bl", "uniquePairId", "Pair.age..MY.",
                     "Migration", "Body.mass..log.", "Passerine...non.passerine","n_pam_cells_sp1",
                     "min_lat_sp1", "max_lat_sp1", "lat_range_sp1", "min_lat_sp2", "max_lat_sp2", "lat_range_sp2", "lat_ov_range", "lat_ov_perc_smrnge",
                     "min_ele_sp1", "max_ele_sp1", "ele_range_sp1", "min_ele_sp2", "max_ele_sp2", "ele_range_sp2", "ele_ov_range", "ele_ov_perc_smrnge",
                     "min_MAT_sp1", "max_MAT_sp1", "MAT_range_sp1", "min_MAT_sp2", "max_MAT_sp2", "MAT_range_sp2", "MAT_ov_range", "MAT_ov_perc_smrnge",
                     "min_VarT_sp1", "max_VarT_sp1", "VarT_range_sp1", "min_VarT_sp2", "max_VarT_sp2", "VarT_range_sp2", "VarT_ov_range", "VarT_ov_perc_smrnge")]; rm(cooneyp)

# sympatric cells.
#  - identify paths that should be 0-cost b/c sympatry & replace with appropriate data.
#     - find set that is shared pts in range 1 and range 2
#     - note n sympatric cells in range 1
#     - find cost, len, and bb cells that correspond to the lonlat pts in share set and replace with appropriate data
setwd("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/PREP/PAM/Data")
load("cbPAM.rdata")
m_a_lonlat <- matrix(paste(m_a_lons,m_a_lats,sep=","),dim(m_a_lons)[1],dim(m_a_lons)[2])
m_a_lonlat[m_a_lonlat == "NA,NA"] <- NA

for (i in 1:nrow(m_a_lonlat)) {
  r12 <- cbPAM[, c("Longitude(x)", "Latitude(y)", mydata$Species.1bl[i], mydata$Species.2bl[i])]
  r12 <- matrix(r12[r12[,3] == 1 & r12[,4] == 1,], ncol = 4)
  r12 <- paste(r12[,1], r12[,2], sep = ",")
  m_a_lonlat[i,][m_a_lonlat[i,] %in% r12] <- "sym"
  m_a_lonlat[i,][m_a_lonlat[i,] %!in% r12 & m_a_lonlat[i,] != "sym" & !is.na(m_a_lonlat[i,])] <- "alo"
}

m_aB_ele_mcosts[m_a_lonlat == "sym"] <- 0
m_aB_ele_plengths[m_a_lonlat == "sym"] <- 0
# fix bblons and bblats later!!!!!

m_aB_MAT_mcosts[m_a_lonlat == "sym"] <- 0
m_aB_MAT_plengths[m_a_lonlat == "sym"] <- 0
# fix bblons and bblats later!!!!!


# *these values are broadly identical, only 2 species disagree -- I think these two species are still running on cluster, check again after re downloading upon run completion
mydata$ele_npaths <- apply(m_aB_ele_mcosts, 1, function(x) sum(!is.na(x))) # n good ele paths (not sympatric, not iso by water)
mydata$MAT_npaths <- apply(m_aB_MAT_mcosts, 1, function(x) sum(!is.na(x))) # n good MAT paths 

mydata$splonmean <- apply(m_a_lons, 1, function(x) mean(x, na.rm = T));mydata$splonmean[is.nan(mydata$splonmean)] <- NA # longitude info (SPECIES)
mydata$splatmean <- apply(m_a_lats, 1, function(x) mean(x, na.rm = T));mydata$splatmean[is.nan(mydata$splatmean)] <- NA # Latitude info (SPECIES)
mydata$spabslatmean <- apply(abs(m_a_lats), 1, function(x) mean(x, na.rm = T));mydata$spabslatmean[is.nan(mydata$spabslatmean)] <- NA # absLatitude info (SPECIES)

mydata$ele_cmin <- apply(m_aB_ele_mcosts, 1, quantile, na.rm = T, probs = 0);mydata$ele_cmin[is.nan(mydata$ele_cmin)] <- NA
mydata$ele_cmean <- apply(m_aB_ele_mcosts, 1, function(x) mean(x, na.rm = T));mydata$ele_cmean[is.nan(mydata$ele_cmean)] <- NA
mydata$ele_cmedian <- apply(m_aB_ele_mcosts, 1, function(x) median(x, na.rm = T));mydata$ele_cmedian[is.nan(mydata$ele_cmedian)] <- NA

mydata$MAT_cmin <- apply(m_aB_MAT_mcosts, 1, quantile, na.rm = T, probs = 0);mydata$MAT_cmin[is.nan(mydata$MAT_cmin)] <- NA
mydata$MAT_cmean <- apply(m_aB_MAT_mcosts, 1, function(x) mean(x, na.rm = T));mydata$MAT_cmean[is.nan(mydata$MAT_cmean)] <- NA
mydata$MAT_cmedian <- apply(m_aB_MAT_mcosts, 1, function(x) median(x, na.rm = T));mydata$MAT_cmedian[is.nan(mydata$MAT_cmedian)] <- NA

# separated by water Y/N (if no paths then yes, if paths then no...pretty easy).

setwd("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Process_Cluster_Outputs/Data")
save(mydata, file = "Species_Barrier_Data_BONES.rdata")



```



btm50 & btm25 - ele mcost
```{r}
mydata$ele_rowmincut <- NA

mydata$ele_50_rowmaxcut <- NA
m_aB_ele_mcosts_btm50 <- m_aB_ele_mcosts
m_aB_ele_plengths_btm50 <- m_aB_ele_plengths


mydata$ele_25_rowmaxcut <- NA
m_aB_ele_mcosts_btm25 <- m_aB_ele_mcosts
m_aB_ele_plengths_btm25 <- m_aB_ele_plengths


mydata$ele_rowmincut <- apply(m_aB_ele_mcosts, 1, quantile, na.rm = T, probs = 0)
mydata$ele_50_rowmaxcut <- apply(m_aB_ele_mcosts, 1, quantile, na.rm = T, probs = 0.50)
mydata$ele_25_rowmaxcut <- apply(m_aB_ele_mcosts, 1, quantile, na.rm = T, probs = 0.25)


for (i in 1:nrow(mydata)){
  m_aB_ele_mcosts_btm50[i,which(m_aB_ele_mcosts[i,] < mydata$ele_rowmincut[i])] <- NA
  m_aB_ele_mcosts_btm50[i,which(m_aB_ele_mcosts[i,] > mydata$ele_50_rowmaxcut[i])] <- NA
  
  m_aB_ele_plengths_btm50[i,which(m_aB_ele_mcosts[i,] < mydata$ele_rowmincut[i])] <- NA
  m_aB_ele_plengths_btm50[i,which(m_aB_ele_mcosts[i,] > mydata$ele_50_rowmaxcut[i])] <- NA
  
  m_aB_ele_mcosts_btm25[i,which(m_aB_ele_mcosts[i,] < mydata$ele_rowmincut[i])] <- NA
  m_aB_ele_mcosts_btm25[i,which(m_aB_ele_mcosts[i,] > mydata$ele_25_rowmaxcut[i])] <- NA
  
  m_aB_ele_plengths_btm25[i,which(m_aB_ele_mcosts[i,] < mydata$ele_rowmincut[i])] <- NA
  m_aB_ele_plengths_btm25[i,which(m_aB_ele_mcosts[i,] > mydata$ele_25_rowmaxcut[i])] <- NA
}

# # checks show working as intended. 
# rowSums(!is.na(m_aB_ele_mcosts[10:20,])); rowMeans(m_aB_ele_mcosts[10:20,], na.rm = T)
# rowSums(!is.na(m_aB_ele_mcosts_btm50[10:20,])); rowMeans(m_aB_ele_mcosts_btm50[10:20,], na.rm = T)
# rowSums(!is.na(m_aB_ele_mcosts_btm25[10:20,])); rowMeans(m_aB_ele_mcosts_btm25[10:20,], na.rm = T)

mydata$ele_cmean_btm50 <- apply(m_aB_ele_mcosts_btm50, 1, function(x) mean(x, na.rm = T));mydata$ele_cmean_btm50[is.nan(mydata$ele_cmean_btm50)] <- NA # mean cost for btm half of paths
mydata$ele_cmean_btm25 <- apply(m_aB_ele_mcosts_btm25, 1, function(x) mean(x, na.rm = T));mydata$ele_cmean_btm25[is.nan(mydata$ele_cmean_btm25)] <- NA # mean cost for btm 25% of paths
```


btm50 & btm25 - MAT mcost
```{r}
mydata$MAT_rowmincut <- NA

mydata$MAT_50_rowmaxcut <- NA
m_aB_MAT_mcosts_btm50 <- m_aB_MAT_mcosts
m_aB_MAT_plengths_btm50 <- m_aB_MAT_plengths


mydata$MAT_25_rowmaxcut <- NA
m_aB_MAT_mcosts_btm25 <- m_aB_MAT_mcosts
m_aB_MAT_plengths_btm25 <- m_aB_MAT_plengths


mydata$MAT_rowmincut <- apply(m_aB_MAT_mcosts, 1, quantile, na.rm = T, probs = 0)
mydata$MAT_50_rowmaxcut <- apply(m_aB_MAT_mcosts, 1, quantile, na.rm = T, probs = 0.50)
mydata$MAT_25_rowmaxcut <- apply(m_aB_MAT_mcosts, 1, quantile, na.rm = T, probs = 0.25)


for (i in 1:nrow(mydata)){
  m_aB_MAT_mcosts_btm50[i,which(m_aB_MAT_mcosts[i,] < mydata$MAT_rowmincut[i])] <- NA
  m_aB_MAT_mcosts_btm50[i,which(m_aB_MAT_mcosts[i,] > mydata$MAT_50_rowmaxcut[i])] <- NA
  
  m_aB_MAT_plengths_btm50[i,which(m_aB_MAT_mcosts[i,] < mydata$MAT_rowmincut[i])] <- NA
  m_aB_MAT_plengths_btm50[i,which(m_aB_MAT_mcosts[i,] > mydata$MAT_50_rowmaxcut[i])] <- NA
  
  m_aB_MAT_mcosts_btm25[i,which(m_aB_MAT_mcosts[i,] < mydata$MAT_rowmincut[i])] <- NA
  m_aB_MAT_mcosts_btm25[i,which(m_aB_MAT_mcosts[i,] > mydata$MAT_25_rowmaxcut[i])] <- NA
  
  m_aB_MAT_plengths_btm25[i,which(m_aB_MAT_mcosts[i,] < mydata$MAT_rowmincut[i])] <- NA
  m_aB_MAT_plengths_btm25[i,which(m_aB_MAT_mcosts[i,] > mydata$MAT_25_rowmaxcut[i])] <- NA
}

# # checks show working as intended. 
# rowSums(!is.na(m_aB_MAT_mcosts[10:20,])); rowMeans(m_aB_MAT_mcosts[10:20,], na.rm = T)
# rowSums(!is.na(m_aB_MAT_mcosts_btm50[10:20,])); rowMeans(m_aB_MAT_mcosts_btm50[10:20,], na.rm = T)
# rowSums(!is.na(m_aB_MAT_mcosts_btm25[10:20,])); rowMeans(m_aB_MAT_mcosts_btm25[10:20,], na.rm = T)

mydata$MAT_cmean_btm50 <- apply(m_aB_MAT_mcosts_btm50, 1, function(x) mean(x, na.rm = T));mydata$MAT_cmean_btm50[is.nan(mydata$MAT_cmean_btm50)] <- NA # mean cost for btm half of paths
mydata$MAT_cmean_btm25 <- apply(m_aB_MAT_mcosts_btm25, 1, function(x) mean(x, na.rm = T));mydata$MAT_cmean_btm25[is.nan(mydata$MAT_cmean_btm25)] <- NA # mean cost for btm 25% of paths


setwd("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Process_Cluster_Outputs/Data")
save(mydata, file = "Species_Barrier_Data_BONES.rdata")
```





