---
title: "JMPH_ANGELA&VINCEexploreModels"
output:
  html_document: default
---

Prepare the workspace.
```{r Top Matter, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, error = FALSE) # rmd options

rm(list = ls()); invisible(gc()) # cleaning

options(scipen = 999) # turn off scientific notation

'%notin%' <- Negate('%in%')

require(ggplot2) # load packages
require(GGally)
require(gridExtra)
require(grid)
require(lattice)
require(ggplotify)
require(quantreg)
require(viridis)
require(caper)
require(splines)
library(dplyr)
library(stringr)
library(maps)
library(brms)
library(caper)
library(ape)
library(EnvStats)
library(forecast)
require (nlme)

```
<br><br><br><br><br>




Load data
```{r Load Data}
# main dataframe ---------------------------------
setwd("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Process_Cluster_Outputs/Data")
load(file = "Species_Barrier_Data_BONES_beefier.rdata")


# phylo ------------------------------------------
setwd("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Other_Input_Data/BirdTrees")
load(file = "BirdTrees.Rdata")
tree <- trees[[1]]; rm(trees) # pick tree (VF GET TREES FROM COONEY!!! and use MCC tree.)
tree <- drop.tip(tree, tree$tip.label[which(tree$tip.label %notin% mydata$Species.1)]) # initial name matching.
mydata <- mydata[which(mydata$Species.1 %in% tree$tip.label),]
rownames(mydata) <- mydata$Species.1

mydata$lat_ov_perc_smrnge[which(mydata$lat_ov_perc_smrnge < 0)] <- 0; # hist(mydata$lat_ov_perc_smrnge, 30)
mydata$ele_ov_perc_smrnge[which(mydata$ele_ov_perc_smrnge < 0)] <- 0; # hist(mydata$ele_ov_perc_smrnge, 30)
mydata$MAT_ov_perc_smrnge[which(mydata$MAT_ov_perc_smrnge < 0)] <- 0; # hist(mydata$MAT_ov_perc_smrnge, 30)
mydatahold <- mydata
```
<br><br><br><br><br>

```{r}
mycost <- "cmean" # OPTIONS: "cmin", "cmean", "cmean_btm50, cmean_btm25, "cmedian
allowmigrants <- F # OPTIONS: T, F
allowsympatry <- F # OPTIONS: T, F
collapsepairs <- T # OPTIONS: T, F
minoverperc <- 0.0
ELEmydata <- mydatahold
MATmydata <- mydatahold
VARTmydata <- mydatahold
```

```{r}
if(allowmigrants == F){
  ELEmydata <- ELEmydata[which(ELEmydata$Migration == 1.0),]
  MATmydata <- MATmydata[which(MATmydata$Migration == 1.0),]
  VARTmydata <- VARTmydata[which(VARTmydata$Migration == 1.0),]
} # retain only non-migrants if asked to do so. 

if(allowsympatry == F){
  ELEmydata <- ELEmydata[which(ELEmydata$ele_cmin > 0),]
  MATmydata <- MATmydata[which(MATmydata$ele_cmin > 0),]
  VARTmydata <- VARTmydata[which(VARTmydata$ele_cmin > 0),]
} # retain only allopatric/parapatric species if asked to do so.

ELEmydata <- ELEmydata[which(ELEmydata$ele_ov_perc_smrnge >= minoverperc | ELEmydata$MAT_ov_perc_smrnge >= minoverperc),]
MATmydata <- MATmydata[which(MATmydata$ele_ov_perc_smrnge >= minoverperc | MATmydata$MAT_ov_perc_smrnge >= minoverperc),]
VARTmydata <- VARTmydata[which(VARTmydata$ele_ov_perc_smrnge >= minoverperc | VARTmydata$MAT_ov_perc_smrnge >= minoverperc),]

a <- seq(1:(nrow(ELEmydata)/2)) # fix pair ids so loop below will function correctly
b <- seq(1:(nrow(ELEmydata)/2))
d <- c()
for (i in 1:length(a)) {
  d <- c(d, a[i], b[i])
}
ELEmydata$uniquePairId <- d
MATmydata$uniquePairId <- d
VARTmydata$uniquePairId <- d

if(collapsepairs == T){
  ELEmypairdata <- ELEmydata[1,]
  mypairs <- unique(ELEmydata$uniquePairId)
  for (i in 1:length(mypairs)) {
    pairData <- ELEmydata[which(ELEmydata$uniquePairId == mypairs[i]), ]
    ELEmypairdata[i,] <- pairData[ which(pairData[, paste0("ele_",mycost)] == min(pairData[, paste0("ele_",mycost)], na.rm = T))[1], ] # choose the single member with the lower path cost. 
  }
  ELEmydata <- ELEmypairdata
  
  MATmypairdata <- MATmydata[1,]
  mypairs <- unique(MATmydata$uniquePairId)
  for (i in 1:length(mypairs)) {
    pairData <- MATmydata[which(MATmydata$uniquePairId == mypairs[i]), ]
    MATmypairdata[i,] <- pairData[ which(pairData[, paste0("MAT_",mycost)] == min(pairData[, paste0("MAT_",mycost)], na.rm = T))[1], ] # choose the single member with the lower path cost. 
  }
  MATmydata <- MATmypairdata
    
  VARTmypairdata <- VARTmydata[1,]
  mypairs <- unique(VARTmypairdata$uniquePairId)
  for (i in 1:length(mypairs)) {
    pairData <- VARTmydata[which(VARTmydata$uniquePairId == mypairs[i]), ]
    VARTmypairdata[i,] <- pairData[ which(pairData[, paste0("VarT_",mycost)] == min(pairData[, paste0("VarT_",mycost)], na.rm = T))[1], ] # choose the single member with the lower path cost. 
  }
  VARTmydata <- VARTmypairdata
}

ELEmydata <- ELEmydata[!is.na(ELEmydata[, paste0("ele_",mycost)]),] # remove NA cases
ELEpruned.tree <-drop.tip(tree, setdiff(tree$tip.label, row.names(ELEmydata))) # clean up tree tips.
ELEmydata$cost <- ELEmydata[, paste0("ele_",mycost)] # easier to work with cost name
ELEmydata$lcost <- log(ELEmydata$cost + abs(min(ELEmydata$cost, na.rm = T)) + 1) # easier to work with lcost name

MATmydata <- MATmydata[!is.na(MATmydata[, paste0("MAT_",mycost)]),] # remove NA cases
MATpruned.tree <-drop.tip(tree, setdiff(tree$tip.label, row.names(MATmydata))) # clean up tree tips.
MATmydata$cost <- MATmydata[, paste0("MAT_",mycost)] # easier to work with cost name
MATmydata$lcost <- log(MATmydata$cost + abs(min(MATmydata$cost, na.rm = T)) + 1) # easier to work with lcost name

VARTmydata <- VARTmydata[!is.na(VARTmydata[, paste0("VarT_",mycost)]),] # remove NA cases
VARTpruned.tree <-drop.tip(tree, setdiff(tree$tip.label, row.names(VARTmydata))) # clean up tree tips.
VARTmydata$cost <- VARTmydata[, paste0("VarT_",mycost)] # easier to work with cost name
VARTmydata$lcost <- log(VARTmydata$cost + abs(min(VARTmydata$cost, na.rm = T)) + 1) # easier to work with lcost name
```



GLOBAL
```{R}
ELEmydata$splatmean <- rowMeans(cbind(ELEmydata$centroid_lat_sp1, ELEmydata$centroid_lat_sp2), na.rm = T)
ELEmydata$splonmean <- rowMeans(cbind(ELEmydata$centroid_lon_sp1, ELEmydata$centroid_lon_sp2), na.rm = T)
ELEmydata$pairmeanelev <- rowMeans(cbind(ELEmydata$mean_ele_sp1, ELEmydata$mean_ele_sp2))
ELEmydata$pairrngelev <- rowMeans(cbind(ELEmydata$ele_range_sp1, ELEmydata$ele_range_sp2))
ELEmydata$splatmean2 <- ELEmydata$splatmean^2

ggpairs(ELEmydata[, c("lcost", "splatmean", "splatmean2", "pairmeanelev", "pairrngelev", "centroid_distance","ele_ov_perc_smrnge", "Pair.age..MY.")], title = paste0("cost = log ", mycost))


ELEmydata <- ELEmydata[order(factor(rownames(ELEmydata), levels = unique(ELEpruned.tree$tip.label))),]
sum(rownames(ELEmydata) != ELEpruned.tree$tip.label)
mymodq <- gls(lcost ~ splatmean + I(splatmean^2) + 
                pairmeanelev + 
                pairrngelev + 
                centroid_distance + 
                ele_ov_perc_smrnge+
                Pair.age..MY.,
              correlation = corPagel(1, phy = ELEpruned.tree), data = ELEmydata, method = "REML")
summary(mymodq)


require(MuMIn)
dd <- dredge(mymodq)

x <- predict(mymodq)
cor(x,log(ELEmydata$lcost))

setwd("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Analyze_Processed_Cluster_Outputs/Data")
pdf(file = "MountainPassFigure_ele50global_newtest.pdf", width = 3.5, height = 3)
# plot Effects of elevation
plot(ELEmydata$splatmean, ELEmydata$lcost, pch = 16, col = rgb(0,0,0,0.7), xlab = "Latitude",
     ylab = "log( Elevation cost )", main = "Global")

# plot fitted quadratic effect
myx <- seq(min(ELEmydata$splatmean), max(ELEmydata$splatmean), by=0.5)
mycoefs<-coef(mymodq)
myy <- mycoefs[1] + mycoefs[2]*myx + mycoefs[3]*myx^2
lines(c(0,0), c(-10,100), lty=2)
lines(myx,myy,col = 'red', lwd=3)
dev.off()
```




```{r}
require(spdep)
require(spmoran)
ELEmydata$splatmean2 <- ELEmydata$splatmean^2
y <- ELEmydata$lcost
x <- ELEmydata[,c("splatmean", "splatmean2", "pairmeanelev", "pairrngelev", "centroid_distance", "ele_ov_perc_smrnge","Pair.age..MY." )]
coords <- cbind(ELEmydata$splonmean, ELEmydata$splatmean)
meig <- meigen(coords=coords)

res <- resf(y=y, x=x, meig=meig, nvc = TRUE)
res
plot_s(res)



res <- resf_vc(y=y, x=x, meig=meig, xconst_nvc_sel = T)
res
plot_s(res)


x <- ELEmydata[,c("splatmean", "splatmean2", "pairmeanelev" ,"pairrngelev","Pair.age..MY.", "ele_ov_perc_smrnge")]
res <- resf_qr(y=y, x=x, meig=meig, boot=TRUE)
plot_qr(res,1)
plot_qr(res,2)
plot_qr(res,3)
plot_qr(res,4)
plot_qr(res,5)
plot_qr(res,6)
plot_qr(res,7)

```

