---
title: "JMPH_EDA_ele_MASS"
output:
  html_document: default
---

Prepare the workspace.
```{r}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, error = FALSE) # rmd options
rm(list = ls()); invisible(gc()) # cleaning
```
<br><br><br><br><br>

Control Block
```{r} 
# f, f, 0.25 looks nice.
allowmigrants <- F # OPTIONS: T, F 
allowsympatry <- F # OPTIONS: T, F
minoverperc <- 0.25
costvar <- "ele" # "ele", "MAT", "VarT"
```
<br><br><br><br><br>

Packages, Prefs, and Functions
```{r, include=FALSE}
options(scipen = 999) # turn off scientific notation
'%notin%' <- Negate('%in%')
require(ggplot2) # load packages
require(GGally)
require(gridExtra)
require(grid)
require(lattice)
require(ggplotify)
require(quantreg)
require(viridis)
require(caper)
require(splines)
library(dplyr)
library(stringr)
library(maps)
library(brms)
library(caper)
library(ape)
library(EnvStats)
library(forecast)
require(nlme)
require(geodist)
require(letsR)
require(spdep)
require(spatialreg)
require(rnaturalearth)
require(rnaturalearthdata)
require(rgeos)
require(sf)
require(rgdal)
require(raster)
require(reshape2)
require(plotrix)
world <- ne_coastline(scale = "medium", returnclass = "sf")


corVince <- function (value, phy, form = ~1, fixed = FALSE) 
{
    # if (value < 0 || value > 1) 
    #     stop("the value of lambda must be between 0 and 1.")
    if (!inherits(phy, "phylo")) 
        stop("object \"phy\" is not of class \"phylo\"")
    attr(value, "formula") <- form
    attr(value, "fixed") <- fixed
    attr(value, "tree") <- phy
    class(value) <- c("corPagel", "corPhyl", "corStruct")
    value
}
```
<br><br><br><br><br>

Load main data
```{r Load Data}
# main dataframe ---------------------------------
setwd("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Process_Cluster_Outputs/Data")
load(file =  "Pair_Barrier_Data_FEB2021.rdata")
mydata <- mypairdata; rm(mypairdata)
rownames(mydata) <- mydata$Species.1
mydatahold <- mydata
```
<br><br><br><br><br>

Impose masks & do calcuations
```{r}
mydata$cost <- mydata[, paste0(costvar, "_c25")] 
mydata <- mydata[!is.na(mydata$cost),]
mydata$lcost <- log( mydata$cost + abs(min( mydata$cost , na.rm = T)) + 1)

mydata$niche_overlap <- mydata[,paste0(costvar, "_ov_perc_smrnge")]
mydata <- mydata[mydata$niche_overlap >= minoverperc,]

if(allowmigrants == F){
  mydata <- mydata[which(mydata$Migration == 1.0),]
} # retain only non-migrants if asked to do so. 

if(allowsympatry == F){
  mydata <- mydata[which(mydata[,paste0(costvar, "_c0")] > 0 ),]
} # retain only allopatric/parapatric species if asked to do so.

mydata$lat <- mydata[,paste0("lat_mean_pair_", costvar, "_c25")]
mydata$lon <- mydata[,paste0("lon_mean_pair_", costvar, "_c25")]
mydata$niche_breadth <- mydata[,paste0(costvar, "_range_pair_mean")]
mydata$niche_position <- rowMeans(cbind(mydata[, paste0("mean_",costvar,"_sp1")], mydata[, paste0("mean_",costvar,"_sp2")]))
mydata$range_size <- rowMeans(cbind(mydata$n_pam_cells_sp1, mydata$n_pam_cells_sp2))
mydata$distance <- mydata[,paste0("centroid_distance_",costvar,"_c25")]
mydata$pair_age <- mydata$Pair.age..MY.

mydata <- mydata[,c("uniquePairId", "Species.1", "Species.2", "Species.1bl", "Species.2bl",
                    "pair_age", "range_size",  "niche_position", "niche_breadth", "niche_overlap",
                    "cost", "lcost", "lat", "lon", "distance")]

distm <- mydata[,c("lon", "lat")]
distm <- geodist(distm, measure = "geodesic")
rownames(distm) <- rownames(mydata)
colnames(distm) <- rownames(mydata)
basecols <- ncol(mydata)

# neightbors
coords<-cbind(mydata$lon, mydata$lat); coords<-as.matrix(coords) ; row.names(coords)<-rownames(mydata)
k1 <- knn2nb(knearneigh(coords, longlat = T))
nb<- dnearneigh(coords,row.names = row.names(coords), d1=0,d2=max(unlist(nbdists(k1, coords, longlat = T))),longlat=T)
```
<br><br><br><br><br>

# load phylo and prune
```{r}
# phylo ------------------------------------------
setwd("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Other_Input_Data/BirdTrees")
load(file = "BirdTrees.Rdata")
tree <- trees[[1]]; rm(trees) # pick tree (VF GET TREES FROM COONEY!!! and use MCC tree.)
tree <- drop.tip(tree, tree$tip.label[which(tree$tip.label %notin% mydata$Species.1)]) # initial name matching.
mydata <- mydata[which(mydata$Species.1 %in% tree$tip.label),]
mydata <- mydata[match(tree$tip.label, mydata$Species.1),]
sum(mydata$Species.1 != tree$tip.label)
```
<br><br><br><br><br>

Select an appropriate miniplot radius
```{r}
plot(density(mydata$distance))
density(mydata$distance)$x[which.max(density(mydata$distance)$y)]
summary(mydata$distance)[1:4]
abline(v=summary(mydata$distance)[1], col="red") # min
abline(v=summary(mydata$distance)[2], col="pink") #25th
abline(v=summary(mydata$distance)[3], col="purple") #50th
abline(v=summary(mydata$distance)[4], col="blue") # mean
abline(v=density(mydata$distance)$x[which.max(density(mydata$distance)$y)]
, col="black")
```


Load and prep the mountain mass raster
```{r}
mtns <- readOGR(dsn="~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Other_Input_Data/GMBA", layer="GMBA Mountain Inventory_v1.2-World", verbose = FALSE)
wdPAM <- "/Users/boterolab1/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/PREP/PAM/Data"
setwd(wdPAM); load("LonLat_BirdPAM_raster.rdata")
mtns <- rasterize(mtns, LonLat_BirdPAM_raster)
mtns@data@values[!is.na(mtns@data@values)] <- 1 # replace mountain IDs with simple coding. 1 for mountain...
mtns@data@values[is.na(mtns@data@values)] <- 0 # ...0 for no mountain
raster::plot(mtns)
raster::plot(world$geometry, add = T)

density(mydata$distance)$x[which.max(density(mydata$distance)$y)] # radius is peak density path distance. 
raster::pointDistance(c(0,0), c(0,8), lonlat = T) # corresponds to a radius of just about 8 degrees.
raster::pointDistance(c(75,75), c(75,(75+8)), lonlat = T) # polar circles are bigger, but not that much bigger. so should be OK.
raster::plot(mtns)
raster::plot(world$geometry, add = T)
draw.circle(70, 40, 8, nv = 1000, border = "hotpink", lty = 1, lwd = 1)
draw.circle(140, -5, 8, nv = 1000, border = "hotpink", lty = 1, lwd = 1)
draw.circle(-80, 10, 8, nv = 1000, border = "hotpink", lty = 1, lwd = 1)
draw.circle(-70, -50, 8, nv = 1000, border = "hotpink",lty = 1, lwd = 1)
```
View any pair
```{r}
i <- 10
coords1<-data.frame(lon=mydata$lon[i], lat=mydata$lat[i]); coordinates(coords1)<-c("lon","lat"); crs(coords1)<-crs(LonLat_BirdPAM_raster) # get coordinates
z <- extract(mtns, coords1, buffer = density(mydata$distance)$x[which.max(density(mydata$distance)$y)])
sum(z[[1]]) / length(z[[1]])
raster::plot(mtns)
raster::plot(world$geometry, add = T)
draw.circle(x=coords1@coords[1], y=coords1@coords[2], 8, nv = 1000, border = "hotpink", lty = 1, lwd = 1)
```


```{r}
mydata$miniplot <- NA
mydata$mtncells <- NA
mydata$mtnmass <- NA
for (i in 1:nrow(mydata)) {
  coords1<-data.frame(lon=mydata$lon[i], lat=mydata$lat[i]); coordinates(coords1)<-c("lon","lat"); crs(coords1)<-crs(LonLat_BirdPAM_raster) # get coordinates
  z <- extract(mtns, coords1, buffer = density(mydata$distance)$x[which.max(density(mydata$distance)$y)])
  mydata$miniplot[i] <- length(z[[1]])
  mydata$mtncells[i] <- sum(z[[1]])
  mydata$mtnmass[i] <- sum(z[[1]]) / length(z[[1]])
}


plot(mydata$lat, mydata$miniplot)
ggplot(world)+
  geom_sf() + 
  geom_point(data = mydata, aes(y=lat, x=lon, color = miniplot)) + 
  scale_color_viridis()


plot(mydata$lat, mydata$mtncells)
ggplot(world)+
  geom_sf() + 
  geom_point(data = mydata, aes(y=lat, x=lon, color = mtncells)) + 
  scale_color_viridis()


plot(mydata$lat, mydata$mtncells)
ggplot(world)+
  geom_sf() + 
  geom_point(data = mydata, aes(y=lat, x=lon, color = mtnmass)) + 
  scale_color_viridis()




plot(mydata$lcost, mydata$mtnmass)

```


Potential problems with edge cases (n=2 cases only..)
```{r}
# this has the potential to misrepresent the pairs close to the EW wrap around border. It affects only 2 pairs at a radius of 8 and does not effect them a lot. (912 instead of 1046 total cells: 13% loss)
d <- mydata[mydata$lon == max(mydata$lon),]
coords1<-data.frame(lon=d$lon, lat=d$lat); coordinates(coords1)<-c("lon","lat"); crs(coords1)<-crs(LonLat_BirdPAM_raster)
z <- extract(mtns, coords1, buffer = density(mydata$distance)$x[which.max(density(mydata$distance)$y)])
length(z[[1]])
raster::plot(mtns)
raster::plot(world$geometry, add = T)
draw.circle(x=coords1@coords[1], y=coords1@coords[2], 8, nv = 1000, border = "hotpink", lty = 1, lwd = 1)

d <- mydata[mydata$lon == max(mydata$lon),]
coords1<-data.frame(lon=10, lat=d$lat); coordinates(coords1)<-c("lon","lat"); crs(coords1)<-crs(LonLat_BirdPAM_raster)
z <- extract(mtns, coords1, buffer = density(mydata$distance)$x[which.max(density(mydata$distance)$y)])
length(z[[1]])
raster::plot(mtns)
raster::plot(world$geometry, add = T)
draw.circle(x=coords1@coords[1], y=coords1@coords[2], 8, nv = 1000, border = "hotpink", lty = 1, lwd = 1)
```





```{r}
wtr <- read_sf("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/ne_50m_ocean/ne_50m_ocean.shp"); plot(wtr)
temp <- mtns
values(temp) <- 100
temp <- mask(temp, wtr)
wtr <- mtns
values(wtr) <- 0
wtr[temp == 100] <- 1; rm(temp)
plot(wtr)




mydata$wtrcells <- NA
mydata$wtrmass <- NA
for (i in 1:nrow(mydata)) {
  coords1<-data.frame(lon=mydata$lon[i], lat=mydata$lat[i]); coordinates(coords1)<-c("lon","lat"); crs(coords1)<-crs(LonLat_BirdPAM_raster) # get coordinates
  z <- extract(wtr, coords1, buffer = density(mydata$distance)$x[which.max(density(mydata$distance)$y)])
  mydata$miniplot[i] <- length(z[[1]])
  mydata$wtrcells[i] <- sum(z[[1]])
  mydata$wtrmass[i] <- sum(z[[1]]) / length(z[[1]])
}


plot(mydata$lat, mydata$miniplot)
ggplot(world)+
  geom_sf() + 
  geom_point(data = mydata, aes(y=lat, x=lon, color = miniplot)) + 
  scale_color_viridis()


plot(mydata$lat, mydata$wtrcells)
ggplot(world)+
  geom_sf() + 
  geom_point(data = mydata, aes(y=lat, x=lon, color = wtrcells)) + 
  scale_color_viridis()


plot(mydata$lat, mydata$wtrmass)
ggplot(world)+
  geom_sf() + 
  geom_point(data = mydata, aes(y=lat, x=lon, color = wtrmass)) + 
  scale_color_viridis()




plot(mydata$lcost, mydata$wtrmass)

```

