---
  title: "JMPH_path_maps"
output:
  html_document: default
---

```{r}
rm(list = ls())
require(rgdal)
require(sf)
require(raster)
require(rgeos)
require(maptools)
require(rnaturalearth)
require(rnaturalearthdata)
require(ggplot2)
wdtopo <- "/Users/boterolab1/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/PREP/Topo/Data"
setwd(wdtopo); load("Elev_raster.rdata")

bb <- extent(-180, 180, -60, 90)
Elev_raster <- crop(Elev_raster, bb, keepres=T)

wdPAM <- "/Users/boterolab1/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/PREP/PAM/Data"
setwd(wdPAM); load("cbPAM.rdata")

mtns <- readOGR(dsn="~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Other_Input_Data/GMBA", layer = "GMBA Mountain Inventory_v1.2-World", verbose = FALSE)
world <- ne_coastline(scale = "medium", returnclass = "sf")
```

```{r}
setwd("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/PREP/MainDataFrame/Data")
load("cooneyp.Rdata")

setwd("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/ClusterFiles_E/outputs_e")

# load("87_ELEVATION_LCP_Paths_for_Cinnyricinclus leucogaster_Hartlaubius auratus_origin_1_to_5000.rdata")
# load("19_ELEVATION_LCP_Paths_for_Neomorphus geoffroyi_Neomorphus radiolosus_origin_1_to_5000.rdata")
load("44_ELEVATION_LCP_Paths_for_Hylophylax naevius_Hylophylax naevioides_origin_1_to_5000.rdata")
pg <- savelist_full_paths_ele

# load("87_ELEVATION_LCP_Paths_for_Hartlaubius auratus_Cinnyricinclus leucogaster_origin_1_to_5000.rdata")
# load("19_ELEVATION_LCP_Paths_for_Neomorphus radiolosus_Neomorphus geoffroyi_origin_1_to_5000.rdata")
load("44_ELEVATION_LCP_Paths_for_Hylophylax naevioides_Hylophylax naevius_origin_1_to_5000.rdata")
gp <- savelist_full_paths_ele

lens <- c()
for (i in 1:length(gp)) {
  lens <- c(lens, nrow(gp[[i]]@lines[[1]]@Lines[[1]]@coords))
}
gp <- gp[which(lens < 100)]

load("44_Main_Batch_Results_origin_1_to_5000_E.rdata")
```

```{r}
which(cooneyp$Species.1bl == "Hylophylax naevius")
i <- which(cooneyp$Species.1bl == "Hylophylax naevius")
x <- cbPAM[,c("Longitude(x)","Latitude(y)",cooneyp$Species.1bl[i])]
x <- x[x[,3] == 1,]

y <- cbPAM[,c("Longitude(x)","Latitude(y)",cooneyp$Species.1bl[i+1])]
y <- y[y[,3] == 1,]

world <- st_crop(world, ymin=-20,ymax=20,xmin=-90,xmax=-45)
CP <- as(extent(-90, -45,-20, 20), "SpatialPolygons")
proj4string(CP) <- CRS(proj4string(mtns))
mtns <- gIntersection(mtns, CP, byid = TRUE)

pdf("test_pg.pdf", width = 10, height = 9)
plot(Elev_raster, col="white",legend = FALSE, ylim = c(-20,20), xlim = c(-90,-45))
plot(world, add = T, lwd = 1, col = "black")
plot(mtns, col = rgb(142/255,94/255,47/255,1), border = NA, lwd = 0.0001, add = T)
points(x, col = rgb(80/255,13/255,73/255,0.75), cex = 1.2, pch = 15)
points(y, col = rgb(71/255,94/255,23/255,0.75), cex = 1.2, pch = 15)
for (j in 1:length(pg)) {
  lines(pg[[j]], col = rgb(223/255,49/255,202/255, 1), lwd = 2.5)
}

dev.off()

pdf("test_gp.pdf", width = 10, height = 9)
plot(Elev_raster, col="white",legend = FALSE, ylim = c(-20,20), xlim = c(-90,-45))
plot(world, add = T, lwd = 1, col = "black")
plot(mtns, col = rgb(142/255,94/255,47/255,1), border = NA, lwd = 0.0001, add = T)
points(x, col = rgb(80/255,13/255,73/255,0.75), cex = 1.2, pch = 15)
points(y, col = rgb(71/255,94/255,23/255,0.75), cex = 1.2, pch = 15)
for (k in 1:length(gp)) {
  lines(gp[[k]], col = rgb(161/255,208/255,65/255, 1), lwd = 2.5)
}

dev.off()



ppaths <- m_aB_ele_mcosts_block["Hylophylax naevius",]
ppaths <- ppaths[!is.na(ppaths)]
pg25 <- pg[which(ppaths < quantile(ppaths, 0.25))]

gpaths <- m_aB_ele_mcosts_block["Hylophylax naevioides",]
gpaths <- gpaths[!is.na(gpaths)]
gp25 <- gp[which(gpaths < quantile(gpaths, 0.25))]

pdf("test_pg25.pdf", width = 10, height = 9)
plot(Elev_raster, col="white",legend = FALSE, ylim = c(-20,20), xlim = c(-90,-45))
plot(world, add = T, lwd = 1, col = "black")
plot(mtns, col = rgb(142/255,94/255,47/255,1), border = NA, lwd = 0.0001, add = T)
points(x, col = rgb(80/255,13/255,73/255,0.75), cex = 1.2, pch = 15)
points(y, col = rgb(71/255,94/255,23/255,0.75), cex = 1.2, pch = 15)
for (j in 1:length(pg25)) {
  lines(pg25[[j]], col = rgb(223/255,49/255,202/255, 1), lwd = 2.5)
}

dev.off()

pdf("test_gp25.pdf", width = 10, height = 9)
plot(Elev_raster, col="white",legend = FALSE, ylim = c(-20,20), xlim = c(-90,-45))
plot(world, add = T, lwd = 1, col = "black")
plot(mtns, col = rgb(142/255,94/255,47/255,1), border = NA, lwd = 0.0001, add = T)
points(x, col = rgb(80/255,13/255,73/255,0.75), cex = 1.2, pch = 15)
points(y, col = rgb(71/255,94/255,23/255,0.75), cex = 1.2, pch = 15)
for (k in 1:length(gp25)) {
  lines(gp25[[k]], col = rgb(161/255,208/255,65/255, 1), lwd = 2.5)
}

dev.off()



ppaths <- m_aB_ele_mcosts_block["Hylophylax naevius",]
ppaths <- ppaths[!is.na(ppaths)]
pg125 <- pg[which(ppaths < quantile(ppaths, 0.125))]

gpaths <- m_aB_ele_mcosts_block["Hylophylax naevioides",]
gpaths <- gpaths[!is.na(gpaths)]
gp125 <- gp[which(gpaths < quantile(gpaths, 0.125))]

pdf("test_pg125.pdf", width = 10, height = 9)
plot(Elev_raster, col="white",legend = FALSE, ylim = c(-20,20), xlim = c(-90,-45))
plot(world, add = T, lwd = 1, col = "black")
plot(mtns, col = rgb(142/255,94/255,47/255,1), border = NA, lwd = 0.0001, add = T)
points(x, col = rgb(80/255,13/255,73/255,0.75), cex = 1.2, pch = 15)
points(y, col = rgb(71/255,94/255,23/255,0.75), cex = 1.2, pch = 15)
for (j in 1:length(pg125)) {
  lines(pg125[[j]], col = rgb(223/255,49/255,202/255, 1), lwd = 2.5)
}

dev.off()

pdf("test_gp125.pdf", width = 10, height = 9)
plot(Elev_raster, col="white",legend = FALSE, ylim = c(-20,20), xlim = c(-90,-45))
plot(world, add = T, lwd = 1, col = "black")
plot(mtns, col = rgb(142/255,94/255,47/255,1), border = NA, lwd = 0.0001, add = T)
points(x, col = rgb(80/255,13/255,73/255,0.75), cex = 1.2, pch = 15)
points(y, col = rgb(71/255,94/255,23/255,0.75), cex = 1.2, pch = 15)
for (k in 1:length(gp125)) {
  lines(gp125[[k]], col = rgb(161/255,208/255,65/255, 1), lwd = 2.5)
}

dev.off()



pdf("test_pg0.pdf", width = 10, height = 9)
plot(Elev_raster, col="white",legend = FALSE, ylim = c(-20,20), xlim = c(-90,-45))
plot(world, add = T, lwd = 1, col = "black")
plot(mtns, col = rgb(142/255,94/255,47/255,1), border = NA, lwd = 0.0001, add = T)
points(x, col = rgb(80/255,13/255,73/255,0.75), cex = 1.2, pch = 15)
points(y, col = rgb(71/255,94/255,23/255,0.75), cex = 1.2, pch = 15)
dev.off()

pdf("test_gp0.pdf", width = 10, height = 9)
plot(Elev_raster, col="white",legend = FALSE, ylim = c(-20,20), xlim = c(-90,-45))
plot(world, add = T, lwd = 1, col = "black")
plot(mtns, col = rgb(142/255,94/255,47/255,1), border = NA, lwd = 0.0001, add = T)
points(x, col = rgb(80/255,13/255,73/255,0.75), cex = 1.2, pch = 15)
points(y, col = rgb(71/255,94/255,23/255,0.75), cex = 1.2, pch = 15)
dev.off()
```

