

```{r Top Matter}
rm(list = ls()); invisible(gc())
require(rgdal)
require(sp)
require(raster)
require(reshape2)
require(abind)
mypath <- "~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/"
```

```{r Load CLUSTER OUTPUTS & Concatonate}
load(paste0(mypath, "ClusterFiles_E/outputs_e/1_Main_Batch_Results_origin_1_to_5000_E.rdata")) # elev outputs base
m_a_bblats_ele <- m_a_bblats_ele_block; rm(m_a_bblats_ele_block)
m_a_bblons_ele <- m_a_bblons_ele_block; rm(m_a_bblons_ele_block)
m_aB_ele_mcosts <- m_aB_ele_mcosts_block; rm(m_aB_ele_mcosts_block)
m_aB_ele_plengths <- m_aB_ele_plengths_block; rm(m_aB_ele_plengths_block)

load(paste0(mypath, "ClusterFiles_MAT/outputs_mat/1_Main_Batch_Results_origin_1_to_5000_MAT.rdata")) # temp
m_a_bblats_MAT <- m_a_bblats_MAT_block; rm(m_a_bblats_MAT_block)
m_a_bblons_MAT <- m_a_bblons_MAT_block; rm(m_a_bblons_MAT_block)
m_aB_MAT_mcosts <- m_aB_MAT_mcosts_block; rm(m_aB_MAT_mcosts_block)
m_aB_MAT_plengths <- m_aB_MAT_plengths_block; rm(m_aB_MAT_plengths_block)

load(paste0(mypath, "ClusterFiles_VART/outputs_vart/1_Main_Batch_Results_origin_1_to_5000_VART.rdata")) # var temp
m_a_bblats_VarT <- m_a_bblats_VarT_block; rm(m_a_bblats_VarT_block)
m_a_bblons_VarT <- m_a_bblons_VarT_block; rm(m_a_bblons_VarT_block)
m_aB_VarT_mcosts <- m_aB_VarT_mcosts_block; rm(m_aB_VarT_mcosts_block)
m_aB_VarT_plengths <- m_aB_VarT_plengths_block; rm(m_aB_VarT_plengths_block)


for(i in 2:200){
  load(paste0(mypath, "ClusterFiles_E/outputs_e/", i, "_Main_Batch_Results_origin_1_to_5000_E.rdata")) # elev concat
  m_a_bblats_ele <- rbind(m_a_bblats_ele, m_a_bblats_ele_block); rm(m_a_bblats_ele_block)
  m_a_bblons_ele <- rbind(m_a_bblons_ele, m_a_bblons_ele_block); rm(m_a_bblons_ele_block)
  m_aB_ele_mcosts <- rbind(m_aB_ele_mcosts, m_aB_ele_mcosts_block); rm(m_aB_ele_mcosts_block)
  m_aB_ele_plengths <- rbind(m_aB_ele_plengths, m_aB_ele_plengths_block); rm(m_aB_ele_plengths_block)

  load(paste0(mypath, "ClusterFiles_MAT/outputs_mat/", i, "_Main_Batch_Results_origin_1_to_5000_MAT.rdata")) # temp
  m_a_bblats_MAT <- rbind(m_a_bblats_MAT, m_a_bblats_MAT_block); rm(m_a_bblats_MAT_block)
  m_a_bblons_MAT <- rbind(m_a_bblons_MAT, m_a_bblons_MAT_block); rm(m_a_bblons_MAT_block)
  m_aB_MAT_mcosts <- rbind(m_aB_MAT_mcosts, m_aB_MAT_mcosts_block); rm(m_aB_MAT_mcosts_block)
  m_aB_MAT_plengths <- rbind(m_aB_MAT_plengths, m_aB_MAT_plengths_block); rm(m_aB_MAT_plengths_block)
  
  load(paste0(mypath, "ClusterFiles_VART/outputs_vart/", i, "_Main_Batch_Results_origin_1_to_5000_VART.rdata")) # temp
  m_a_bblats_VarT <- rbind(m_a_bblats_VarT, m_a_bblats_VarT_block); rm(m_a_bblats_VarT_block)
  m_a_bblons_VarT <- rbind(m_a_bblons_VarT, m_a_bblons_VarT_block); rm(m_a_bblons_VarT_block)
  m_aB_VarT_mcosts <- rbind(m_aB_VarT_mcosts, m_aB_VarT_mcosts_block); rm(m_aB_VarT_mcosts_block)
  m_aB_VarT_plengths <- rbind(m_aB_VarT_plengths, m_aB_VarT_plengths_block); rm(m_aB_VarT_plengths_block)

  print(paste0("done ", i))
}
```

```{r Save}
setwd("~/Box Sync/CB_VF_Shared/Dry_Lab/Projects/JMPH/Process_Cluster_Outputs/Data")
save(m_a_bblats_ele, m_a_bblons_ele, m_aB_ele_mcosts, m_aB_ele_plengths, file = "Elevation_Results_Concat.rdata")
save(m_a_bblats_MAT, m_a_bblons_MAT, m_aB_MAT_mcosts, m_aB_MAT_plengths, file = "MAT_Results_Concat.rdata")
save(m_a_bblats_VarT, m_a_bblons_VarT, m_aB_VarT_mcosts, m_aB_VarT_plengths, file = "VarT_Results_Concat.rdata")
```




